name: Make sure npm install works
run-name: ${{ github.actor }} makes sure npm install works
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v3
        name: Setup Node.js
      - run: |
          npm install
          npm start