name: Build and Publish
run-name: ${{ github.actor }} builds and publishes the app
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v3
        name: Setup Node.js
      - run: |
          echo > env<<EOF
          REACT_APP_API_KEY=$REACT_APP_API_KEY
          REACT_APP_MERCHANT_ID=$REACT_APP_MERCHANT_ID
          EOF
        working-directory: ./client-app
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_MERCHANT_ID: ${{ secrets.REACT_APP_MERCHANT_ID }}
        name: Generate env file
      - uses: easingthemes/ssh-deploy@main
        name: Sync build result to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "client-app/"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/publish"
      - uses: easingthemes/ssh-deploy@main
        name: Sync start.sh to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "deployments/start.sh"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/"
      - name: Cleanup env file
        run: |
          rm -f env
        working-directory: ./client-app