name: Build and Publish
run-name: ${{ github.actor }} builds and publishes the app
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v3
        name: Setup Node.js
      - run: |
          echo HOST=${HOST} > .env
          echo PORT=${PORT} >> .env
          echo REACT_APP_API_KEY=${REACT_APP_API_KEY} >> .env
          echo REACT_APP_MERCHANT_ID=${REACT_APP_MERCHANT_ID} >> .env
        working-directory: ./client-app
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_MERCHANT_ID: ${{ secrets.REACT_APP_MERCHANT_ID }}
          HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          PORT: 3001
        name: Generate frontend env file
      - run: |
          npm install
          npm run build
        working-directory: ./client-app
        name: Build front end
      - uses: easingthemes/ssh-deploy@main
        name: Sync build result to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "client-app/build/"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/publish"
      - name: Cleanup env file
        run: |
          rm -f .env
        working-directory: ./client-app
      - uses: easingthemes/ssh-deploy@main
        name: Sync start.sh to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "deployments/start.sh"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/"
      - run: |
          echo HOST=${HOST} > .env
          echo PORT=${PORT} >> .env
        working-directory: ./proxy_server
        env:
          HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          PORT: 3001
        name: Generate proxy env file
      - run: |
          npm install
        working-directory: ./proxy_server
        name: Build proxy server
      - uses: easingthemes/ssh-deploy@main
        name: Sync proxy server to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "proxy_server/"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/proxy_server"
      - uses: easingthemes/ssh-deploy@main
        name: Sync proxy_server.sh to deployment server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "deployments/proxy_server.sh"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/"