name: Build and Publish
run-name: ${{ github.actor }} builds and publishes the app
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - uses: actions/setup-node@v3
        name: Setup Node.js
      - run: |
          npm install
          npm run build
        working-directory: ./client-app
      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "client-app/build/"
          REMOTE_HOST: ${{ secrets.BUILD_HOST_ADDRESS }}
          REMOTE_USER: "omatab"
          TARGET: "/home/omatab/publish"